name: Issue Checker

on:
  issues:
    types: [opened, edited]

jobs:
  check-permission:
    runs-on: ubuntu-latest
    outputs:
      require-result: ${{ steps.checkUser.outputs.require-result }}
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          require: 'write'

  log-conditions:
    runs-on: ubuntu-latest
    needs: check-permission
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}
      ISSUE_STATE: ${{ github.event.issue.state }}
      REQUIRE_RESULT: ${{ needs.check-permission.outputs.require-result }}
    steps:
      - run: echo "require-result = $REQUIRE_RESULT"
      - run: echo "issue state = $ISSUE_STATE"
      - run: echo "contains '[Feature Request]' in title: ${{ contains(env.ISSUE_TITLE, '[Feature Request]') }}"
      - run: echo "contains 'https://github.com' in body: ${{ contains(env.ISSUE_BODY, 'https://github.com') }}"

  check-open:
    runs-on: ubuntu-latest
    needs: check-permission
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}
      ISSUE_STATE: ${{ github.event.issue.state }}
      REQUIRE_RESULT: ${{ needs.check-permission.outputs.require-result }}
    if: env.REQUIRE_RESULT == 'false' && env.ISSUE_STATE == 'open' && contains(env.ISSUE_TITLE, '[Feature Request]') == false && contains(env.ISSUE_BODY, 'https://github.com') == false && contains(env.ISSUE_BODY, 'https://stackblitz.com') == false && contains(env.ISSUE_BODY, 'https://codesandbox.io') == false
    steps:
      - uses: actions-cool/maintain-one-comment@v3
        with:
          body: 由于缺乏足够的信息(github、stackblitz、codesandbox等可复现仓库)，我们暂时关闭了该 Issue。请修改（不要回复） Issue 提供[最小重现](https://stackoverflow.com/help/minimal-reproducible-example)以重新开启。谢谢。如果只是单独的技术咨询，可移步 https://qiankun.umijs.org/#-community 交流~
      - uses: actions-cool/issues-helper@v3
        with:
          actions: close-issue

  check-close:
    runs-on: ubuntu-latest
    needs: check-permission
    env:
      ISSUE_BODY: ${{ github.event.issue.body }}
      ISSUE_STATE: ${{ github.event.issue.state }}
      REQUIRE_RESULT: ${{ needs.check-permission.outputs.require-result }}
    if: env.REQUIRE_RESULT == 'false' && env.ISSUE_STATE == 'closed' && (contains(env.ISSUE_BODY, 'https://github.com') == true || contains(env.ISSUE_BODY, 'https://stackblitz.com') == true || contains(env.ISSUE_BODY, 'https://codesandbox.io') == true)
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: open-issue
